package governance.plugin.util;

import governance.plugin.common.XmlParser;
import org.apache.maven.model.Model;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.project.MavenProject;

import java.io.File;

/**
 * Created by jayanga on 2/9/14.
 */
public class MavenProjectHelper {

    public static MavenProject createMavenProject(File file) throws MojoExecutionException {

        Model model = XmlParser.parsePom(file);
        if (model == null){
            throw new MojoExecutionException("Error while processing  " + file.getAbsoluteFile());
        }

        // Creating a module representing the artifact generated by pom file
        MavenProject project = new MavenProject(model);

        return project;
    }
}
