package governance.plugin.rxt.service;

import governance.plugin.common.GovernanceSOAPMessageCreator;
import governance.plugin.rxt.AbstractAssetCreator;
import governance.plugin.util.PathNameResolver;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.logging.Log;

import java.util.Map;

/**
 * Created by jayanga on 2/9/14.
 */
public class ServiceCreator extends AbstractAssetCreator {

    public static final String GREG_SERVICE_RESOURCE_PATH = "/trunk/services/";

    Log logger;
    public ServiceCreator(Log logger, String gregServiceUrl) throws MojoExecutionException {
        super(gregServiceUrl, "Service.ServiceHttpsSoap12Endpoint");
        this.logger = logger;
    }

    public boolean create(Map<String, String> parameters) throws MojoExecutionException {

        String name = parameters.get("name");
        String namespace = parameters.get("namespace");
        String version = parameters.get("version");
        String type = parameters.get("type");
        String description = parameters.get("description");

        description = (description != null && description != "")? description: "generated by maven-governance-plugin.";

        String servicePath = getResourcePath(new String[]{name, namespace});

        String createServiceRequst =
                GovernanceSOAPMessageCreator.createAddServiceRequest(name
                        , namespace
                        , version
                        , type
                        , description);

        logger.debug("Service creation request. [" + createServiceRequst + "]");

        boolean isServiceCreated = super.createAsset(servicePath, createServiceRequst);

        if (logger.isInfoEnabled()){
            if (isServiceCreated){
                logger.info("Request sent to create Service: "+ name);
            }else{
                logger.info("Service already available: " + name);
            }
        }

        return isServiceCreated;
    }

    @Override
    public boolean create(Object[] parameters) throws MojoExecutionException {
        return false;
    }

    @Override
    public String getResourcePath(String[] parameters) throws MojoExecutionException {
        String name = parameters[0];
        String namespace = parameters[1];

        return PathNameResolver.getResourcePath(name, namespace, ServiceCreator.GREG_SERVICE_RESOURCE_PATH);
    }
}
